name: DOG
main: no.runsafe.dog.DOGPlugin
version: 1.1.@BUILD@
author: Kruithne
authors: [mortenn]
description: The almighty DOG
commands:
  dog:
    description: A collection of commands to control DOG
